

PREFIX daont: <http://www.semanticweb.org/daont#>
PREFIX dpv: <https://w3c.github.io/dpv/2.2/dpv/#>

SELECT DISTINCT 
    ?b2gSharing 
    ?publicBody 
    ?holder
    ?action 
    ("COMPETITIVE_PRODUCT_DEVELOPMENT" AS ?violationType)
    ("Article 19(2)(a) VIOLATED: Public body used data to develop competing product" AS ?details)
WHERE {
  ?b2gSharing a daont:B2GDataSharing ;
              daont:governedBy ?contract .
  ?contract dpv:hasRecipient ?publicBody .
  ?publicBody a daont:PublicSectorBody .
  ?publicBody a daont:DataRecipient .
  ?holder a daont:DataHolder ; #WatchManufacturer
          dpv:hasData ?data .  #CharlieHealthData
  ?holder dpv:hasRecipient ?publicBody .
  
  ?publicBody daont:performsAction ?action .
  ?action a daont:UseDataToDevelopCompetingProduct .
}
ORDER BY ?publicBody



#### OUTPUTS: 

# b2gSharing || publicBody || holder || action || violationType || details
# http://www.semanticweb.org/daont#b2gSharingGonzalo || http://www.semanticweb.org/daont#HealthAuthority || http://www.semanticweb.org/daont#watchManufacturer || http://www.semanticweb.org/daont#UsesDataToDevelopCompetingProduct1 || "COMPETITIVE_PRODUCT_DEVELOPMENT" || "Article 19(2)(a) VIOLATED: Public body used data to develop competing product"